---

name: 'debug'
description: 'debug our environment execution'

branding:
  icon: chevron-down
  color: gray-dark

runs:
  using: composite
  steps:
    - run: |
        whoami
        ls -alh
        pwd
        df -h
        free -m
      shell: bash